package sea.controllers;

import java.util.ArrayList;
import java.util.Optional;
import javax.annotation.PostConstruct;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import sea.models.User;
import sea.models.Event;
import sea.handlers.UserRepository;
import sea.handlers.EventRepository;

@CrossOrigin(origins = "http://localhost:4200")
@Controller // This means that this class is a Controller
@RequestMapping(path = "/sea") // This means URL's start with /demo (after
								// Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
				// Which is auto-generated by Spring, we will use it to handle
				// the data
	private UserRepository userRepository;

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private EventRepository eventRepository;

	@PostConstruct
	public void init() {
		loadData();
	}

	@GetMapping(path = "/loadData") // Map ONLY GET Requests
	public @ResponseBody String loadData() {

		// Creation des utilisateurs
		User u1, u2, u3, u4;

		u1 = new User();
		u2 = new User();
		u3 = new User();
		u4 = new User();

		u1.setName("User 1");
		u2.setName("User 2");
		u3.setName("User 3");
		u4.setName("test");
		u4.setPassword("test");

		ArrayList<User> listU = new ArrayList<User>();
		listU.add(u1);
		listU.add(u2);
		listU.add(u3);
		listU.add(u4);

		userRepository.saveAll(listU);

		// Creation des evenements

		Event e1, e2, e3;
		e1 = new Event();
		e2 = new Event();
		e3 = new Event();

		e1.setName("Event 1");
		e1.setStartDate("2018-03-10 15:00:00");
		e1.setEndDate("2018-03-10 16:00:00");
		e1.setDescription("Couscous party");

		e2.setName("Event 2");
		e2.setStartDate("2018-03-11 14:00:00");
		e2.setEndDate("2018-03-11 16:00:00");
		e2.setDescription("baby foot");

		e3.setName("Event 3");
		e3.setStartDate("2018-03-16 10:00:00");
		e3.setEndDate("2018-03-16 12:00:00");
		e3.setDescription("perles");

		// liens
		e1.addUser(u2);
		e1.addUser(u3);

		e2.addUser(u1);

		e3.addUser(u3);

		ArrayList<Event> list = new ArrayList<Event>();
		list.add(e1);
		list.add(e2);
		list.add(e3);

		eventRepository.saveAll(list);
		return "Data loaded";
	}

	@GetMapping(path = "/detach") // Map ONLY GET Requests
	public @ResponseBody String detach() {

		Optional<Event> event = eventRepository.findById(1);
		String s = "no detach";

		if (event.isPresent()) {
			Event e = event.get();
			e.clearUsers();
			eventRepository.save(e);
			s = "detach";
		}

		return s;
	}
}